config/routes.rb
Cardinform::Application.routes.draw do

  root to: 'pages#home'
  match '/about',     to: 'pages#about'
  match '/privacy',   to: 'pages#privacy'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :last_updated                              ,
                  :product_id                                ,
                  :name                                      ,
                  :description                               ,
                  :short_description                         ,
                  :image_path                                ,
                  :url                                       ,
                  :intro_apr                                 ,
                  :q_intro_apr                               ,
                  :intro_apr_period                          ,
                  :q_intro_apr_period                        ,
                  :regular_apr                               ,
                  :q_regular_apr                             ,
                  :annual_fee                                ,
                  :q_annual_fee                              ,
                  :credit_needed                             ,
                  :q_credit_needed                           ,
                  :balance_transfers                         ,
                  :q_balance_transfers                       ,
                  :transfer_fee_pin                          ,
                  :q_transfer_fee_pin                        ,
                  :transaction_fee_signature                 ,
                  :q_transaction_fee_signature               ,
                  :load_fee                                  ,
                  :q_load_fee                                ,
                  :atm_fee                                   ,
                  :q_atm_fee                                 ,
                  :activation_fee                            ,
                  :q_activation_fee                          ,
                  :balance_transfer_intro_apr                ,
                  :q_balance_transfer_intro_apr              ,
                  :balance_transfer_intro_apr_period         ,
                  :q_balance_transfer_intro_apr_period       ,
                  :balance_transfer_goto_rate                ,
                  :q_balance_transfer_goto_rate              ,
                  :cash_advance_goto_rate                    ,
                  :q_cash_advance_goto_rate                  ,
                  :penalty_goto_rate                         ,
                  :q_penalty_goto_rate                       ,
                  :late_fee                                  ,
                  :q_late_fee                                ,
                  :cash_advance_fee                          ,
                  :q_cash_advance_fee                        ,
                  :balance_transfer_fee                      ,
                  :q_balance_transfer_fee                    ,
                  :foreign_currency_exchange_fee             ,
                  :q_foreign_currency_exchange_fee           ,
                  :issuer                                    ,
                  :feature_flag                              ,
                  :popular_flag                              ,
                  :low_apr_feature_flag                      ,
                  :rewards_feature_flag                      , 
                  :business_feature_flag                     , 
                  :bad_credit_feature_flag                   , 
                  :student_feature_flag                      
  
  validates :product_id, presence: true, uniqueness: true
  validates(:name, presence: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def privacy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Cardinform"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://cardinform.com/">Cardinform Inc.</a>
		by Mark
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Privacy Policy", privacy_path %></li>
			<li><a href="http://cardinform.com/">Cardinform</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Cardinform", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home",						root_path %></li>
					<li><%= link_to "About Us",				about_path %></li>
					<li><%= link_to "Privacy Policy",	privacy_path%></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if IE 9]-->
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		
		<%= yield %>
		
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to Cardinform</h1>
	
	<h2>
		Press the below button to test go to the Product page
	</h2>
	
	<%= link_to "Admin", "#", class: "btn btn-large btn-primary" %>
			
			
</div>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>